config/routes.rb
ContactForm::Application.routes.draw do
  resources :customer_feedbacks

  

end

app/models/customer_feedback.rb
class CustomerFeedback < ActiveRecord::Base
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :description
  validates_presence_of :subject
  validates_presence_of :email_address

  validates_format_of :email_address,
    with: /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customer_feedbacks_controller.rb
class CustomerFeedbacksController < ApplicationController
  # before_action :get_customer_feedback_record, only: [:show, :edit, :update, :destroy]
  
   def index
    @customer_feedbacks = CustomerFeedback.all
  end

  def new
    @customer_feedback = CustomerFeedback.new
  end

  def show
    @customer_feedback = CustomerFeedback.find(params[:id])
  end

  def create
    @customer_feedback = CustomerFeedback.new(reg_params)
    if @customer_feedback.save
      redirect_to @customer_feedback, notice: 'Your message was successfully sent'
    else
      render :new
    end
  end

  def destroy
    @customer_feedback = CustomerFeedback.find(params[:id])
    @customer_feedback.destroy
    respond_to do |format|
      format.html { redirect_to customer_feedbacks_path }
      format.json { head :no_content}
    end
  end

  protected
  def reg_params
    params.require(:customer_feedback).permit(
      :first_name,
      :last_name,
      :email_address,
      :subject,
      :description)
  end

  # def send_message
    # @customer_feedback = CustomerFeedback.find(params[:id])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customer_feedbacks/_form.html.erb
<%= form_for(@customer_feedback) do |f| %>
  <% if @customer_feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer_feedback.errors.count, "error") %> prohibited this menu item from being saved:</h2>

      <ul>
      <% @customer_feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %> 

app/views/customer_feedbacks/index.html.erb
<h1>Customer Feedback and Inquiries</h1>

<table>
  <thead>
    <strong>Messages</strong>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.subject %></td>
        <td><%= link_to 'Show', customer_feedback_path(feedback) %></td>
        <td><%= link_to 'Edit', edit_customer_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', customer_feedback_path(feedback), method: :delete, data: { confirm: 'Are you sure?' } %></td>
<!--         delete is HTTP verb used to hit the Rails destroy action
        destroy is the Rails action -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customer_feedbacks/new.html.erb
<h1>Send Feedback to DogHub</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_feedbacks_path %>

app/views/customer_feedbacks/show.html.erb
<p>
  <strong>Inquiries:</strong>
  <%= @customer_feedback.first_name %>
</p>

<!-- <p>
  <strong>Last name:</strong>
  <%= @customer_feedback.last_name %>
</p> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactForm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>

<%= yield %>

</body>
</html>